"""fan_out worker 测试：覆盖 wmt 血缘 fan-out / hide / 幂等 / 租户隔离等路径。"""

from sqlalchemy import text

from app.core.ids import new_uuid
from app.workers.fan_out import (
    hide_tenant_companies_for_cancelled_keyword,
    run_fan_out_for_tenant_keyword,
)
from tests.helpers import make_engine


async def _setup_wmt_tables(conn) -> None:
    """创建测试用临时表（wmt schema）。"""
    stmts = [
        """
        CREATE TEMP TABLE keyword_master (
          id uuid PRIMARY KEY,
          keyword text NOT NULL,
          keyword_normalized text NOT NULL UNIQUE
        ) ON COMMIT DROP;
        """,
        """
        CREATE TEMP TABLE waimaotong_clean_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          company_name text,
          country_iso3 char(3),
          sys_company_id uuid,
          domain text,
          industry text,
          sub_industry text,
          product_tags jsonb,
          contacts_count int DEFAULT 0,
          keyword_master_ids uuid[] NOT NULL DEFAULT '{}'
        ) ON COMMIT DROP;
        """,
        """
        CREATE TEMP TABLE tenant_keyword (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL,
          keyword_master_id uuid NOT NULL,
          keyword_raw text NOT NULL,
          status text NOT NULL DEFAULT 'active',
          UNIQUE (tenant_id, keyword_master_id)
        ) ON COMMIT DROP;
        """,
        """
        CREATE TEMP TABLE tenant_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL,
          clean_company_id bigint NOT NULL,
          business_status text NOT NULL DEFAULT 'new',
          data_status text NOT NULL DEFAULT 'ready',
          visibility_status text NOT NULL DEFAULT 'hidden',
          model_score numeric,
          score numeric,
          note text,
          tags text[] DEFAULT '{}',
          updated_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (tenant_id, clean_company_id)
        ) ON COMMIT DROP;
        """,
        """
        CREATE TEMP TABLE group_members (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL,
          tenant_company_id bigint,
          tenant_contact_id bigint
        ) ON COMMIT DROP;
        """,
        """
        CREATE TEMP TABLE scoring_jobs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL,
          tenant_company_id bigint NOT NULL,
          status text NOT NULL DEFAULT 'pending'
        ) ON COMMIT DROP;
        """,
        """
        CREATE TEMP TABLE company_scores (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL,
          tenant_company_id bigint NOT NULL
        ) ON COMMIT DROP;
        """,
    ]
    for s in stmts:
        await conn.execute(text(s))


async def _insert_km(conn, km_id: str, keyword: str) -> None:
    await conn.execute(
        text("INSERT INTO keyword_master (id, keyword, keyword_normalized) VALUES (:id, :kw, :kn)"),
        {"id": km_id, "kw": keyword, "kn": keyword.lower()},
    )


async def _insert_wmt_clean(conn, *, company_name: str, km_ids: list[str], contacts_count: int = 5, domain: str | None = "example.com", industry: str | None = "PCB") -> int:
    row = await conn.execute(
        text("""
            INSERT INTO waimaotong_clean_companies
              (company_name, country_iso3, keyword_master_ids, contacts_count, domain, industry)
            VALUES (:name, 'CHN', CAST(:km_ids AS uuid[]), :cc, :domain, :industry)
            RETURNING id
        """),
        {"name": company_name, "km_ids": km_ids, "cc": contacts_count, "domain": domain, "industry": industry},
    )
    return row.scalar_one()


async def _subscribe(conn, tenant_id: str, km_id: str, keyword: str = "pcb") -> None:
    await conn.execute(
        text("""
            INSERT INTO tenant_keyword (tenant_id, keyword_master_id, keyword_raw, status)
            VALUES (:tid, :kid, :kw, 'active')
            ON CONFLICT (tenant_id, keyword_master_id) DO UPDATE SET status = 'active'
        """),
        {"tid": tenant_id, "kid": km_id, "kw": keyword},
    )


async def _count_visible(conn, tenant_id: str) -> int:
    r = await conn.execute(
        text("SELECT count(*) FROM tenant_companies WHERE tenant_id = :tid AND visibility_status = 'visible'"),
        {"tid": tenant_id},
    )
    return r.scalar_one()


# ── 1. clean 主路径 ──────────────────────────────────────────

async def test_fan_out_inserts_wmt_companies_for_subscribed_keyword() -> None:
    """wmt 公司有 keyword_master_ids 匹配租户关键词 → 写入 tenant_companies。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            wmt_id = await _insert_wmt_clean(conn, company_name="Test PCB Co", km_ids=[km_id])
            await _subscribe(conn, tid, km_id)

            result = await run_fan_out_for_tenant_keyword(conn, tid, km_id)

            rows = (await conn.execute(
                text("SELECT clean_company_id, visibility_status, data_status FROM tenant_companies WHERE tenant_id = :tid"),
                {"tid": tid},
            )).mappings().all()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["inserted"] == 1
    assert len(rows) == 1
    assert rows[0]["clean_company_id"] == wmt_id
    assert rows[0]["visibility_status"] == "visible"
    assert rows[0]["data_status"] == "ready"


# ── 4. fan-out 防回归：clean_company_id 必须能 JOIN wmt 表 ──

async def test_fan_out_ids_are_wmt_clean_ids() -> None:
    """fan_out 写入的 clean_company_id 必须是 waimaotong_clean_companies.id。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="WMT Co", km_ids=[km_id])
            await _subscribe(conn, tid, km_id)
            await run_fan_out_for_tenant_keyword(conn, tid, km_id)

            joinable = (await conn.execute(
                text("""
                    SELECT count(*) FROM tenant_companies tc
                    JOIN waimaotong_clean_companies wc ON wc.id = tc.clean_company_id
                    WHERE tc.tenant_id = :tid
                """),
                {"tid": tid},
            )).scalar_one()
            total = (await conn.execute(
                text("SELECT count(*) FROM tenant_companies WHERE tenant_id = :tid"),
                {"tid": tid},
            )).scalar_one()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert joinable == total
    assert total > 0


# ── 5. 幂等 ──────────────────────────────────────────────────

async def test_fan_out_idempotent() -> None:
    """重复 fan_out 不产生重复记录。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="Idempotent Co", km_ids=[km_id])
            await _subscribe(conn, tid, km_id)

            r1 = await run_fan_out_for_tenant_keyword(conn, tid, km_id)
            r2 = await run_fan_out_for_tenant_keyword(conn, tid, km_id)
            count = await _count_visible(conn, tid)
        finally:
            await tx.rollback()
            await engine.dispose()

    assert r1["inserted"] == 1
    assert r2["inserted"] == 0
    assert count == 1


# ── 6. hide 正确隐藏 ─────────────────────────────────────────

async def test_hide_hides_companies_when_keyword_cancelled() -> None:
    """取消关键词后，该关键词的公司被隐藏。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="Hide Co", km_ids=[km_id])
            await _subscribe(conn, tid, km_id)
            await run_fan_out_for_tenant_keyword(conn, tid, km_id)

            assert await _count_visible(conn, tid) == 1

            await conn.execute(
                text("UPDATE tenant_keyword SET status = 'deleted' WHERE tenant_id = :tid AND keyword_master_id = :kid"),
                {"tid": tid, "kid": km_id},
            )
            result = await hide_tenant_companies_for_cancelled_keyword(conn, tenant_id=tid, keyword_master_id=km_id)

            assert await _count_visible(conn, tid) == 0
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["hidden"] == 1


# ── 7. hide 保留多关键词公司 ──────────────────────────────────

async def test_hide_preserves_multi_keyword_company() -> None:
    """公司有多个关键词覆盖 → 删除一个关键词后公司仍可见。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_a = str(new_uuid())
            km_b = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_a, "PCB")
            await _insert_km(conn, km_b, "LED")
            await _insert_wmt_clean(conn, company_name="Multi KW Co", km_ids=[km_a, km_b])
            await _subscribe(conn, tid, km_a, "PCB")
            await _subscribe(conn, tid, km_b, "LED")
            await run_fan_out_for_tenant_keyword(conn, tid, km_a)

            await conn.execute(
                text("UPDATE tenant_keyword SET status = 'deleted' WHERE tenant_id = :tid AND keyword_master_id = :kid"),
                {"tid": tid, "kid": km_a},
            )
            result = await hide_tenant_companies_for_cancelled_keyword(conn, tenant_id=tid, keyword_master_id=km_a)

            visible = await _count_visible(conn, tid)
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["hidden"] == 0
    assert visible == 1


# ── 10. data_status 使用 wmt 字段 ────────────────────────────

async def test_data_status_missing_contacts() -> None:
    """contacts_count=0 → data_status='missing_contacts'。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="No Contacts Co", km_ids=[km_id], contacts_count=0)
            await _subscribe(conn, tid, km_id)
            await run_fan_out_for_tenant_keyword(conn, tid, km_id)

            ds = (await conn.execute(
                text("SELECT data_status FROM tenant_companies WHERE tenant_id = :tid"),
                {"tid": tid},
            )).scalar_one()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert ds == "missing_contacts"


async def test_data_status_insufficient_data() -> None:
    """domain/industry/product_tags 全为 NULL → data_status='insufficient_data'。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="Sparse Co", km_ids=[km_id], contacts_count=3, domain=None, industry=None)
            await _subscribe(conn, tid, km_id)
            await run_fan_out_for_tenant_keyword(conn, tid, km_id)

            ds = (await conn.execute(
                text("SELECT data_status FROM tenant_companies WHERE tenant_id = :tid"),
                {"tid": tid},
            )).scalar_one()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert ds == "insufficient_data"


# ── 11 & 12. keyword_master_ids NULL 或空数组 ────────────────

async def test_fan_out_skips_no_lineage_null() -> None:
    """keyword_master_ids 为空数组 → 不写入 tenant_companies。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="No Lineage Co", km_ids=[])
            await _subscribe(conn, tid, km_id)

            result = await run_fan_out_for_tenant_keyword(conn, tid, km_id)
            count = await _count_visible(conn, tid)
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["inserted"] == 0
    assert count == 0


# ── 14. 多条 wmt_raw 映射同一 clean → 幂等 ───────────────────

async def test_fan_out_dedup_same_company_multiple_keywords() -> None:
    """同一公司匹配多个关键词 → (tenant_id, clean_company_id) 幂等，不重复。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_a = str(new_uuid())
            km_b = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_a, "PCB")
            await _insert_km(conn, km_b, "LED")
            await _insert_wmt_clean(conn, company_name="Multi Match Co", km_ids=[km_a, km_b])
            await _subscribe(conn, tid, km_a, "PCB")
            await _subscribe(conn, tid, km_b, "LED")

            await run_fan_out_for_tenant_keyword(conn, tid, km_a)
            await run_fan_out_for_tenant_keyword(conn, tid, km_b)
            count = (await conn.execute(
                text("SELECT count(*) FROM tenant_companies WHERE tenant_id = :tid"),
                {"tid": tid},
            )).scalar_one()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert count == 1


# ── 16. 租户隔离 ─────────────────────────────────────────────

async def test_fan_out_tenant_isolation() -> None:
    """不同租户只看到自己关键词匹配的公司。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_a = str(new_uuid())
            km_b = str(new_uuid())
            tid_a = str(new_uuid())
            tid_b = str(new_uuid())
            await _insert_km(conn, km_a, "PCB")
            await _insert_km(conn, km_b, "LED")
            await _insert_wmt_clean(conn, company_name="PCB Only Co", km_ids=[km_a])
            await _insert_wmt_clean(conn, company_name="LED Only Co", km_ids=[km_b])
            await _subscribe(conn, tid_a, km_a, "PCB")
            await _subscribe(conn, tid_b, km_b, "LED")

            await run_fan_out_for_tenant_keyword(conn, tid_a, km_a)
            await run_fan_out_for_tenant_keyword(conn, tid_b, km_b)

            count_a = await _count_visible(conn, tid_a)
            count_b = await _count_visible(conn, tid_b)
        finally:
            await tx.rollback()
            await engine.dispose()

    assert count_a == 1
    assert count_b == 1


# ── no subscription → skip ───────────────────────────────────

async def test_fan_out_skips_when_not_subscribed() -> None:
    """租户未订阅该关键词 → 不写入。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            await _insert_wmt_clean(conn, company_name="Orphan Co", km_ids=[km_id])

            result = await run_fan_out_for_tenant_keyword(conn, tid, km_id)
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["inserted"] == 0


# ── keyword_master 不存在 → skip ─────────────────────────────

async def test_fan_out_skips_unknown_keyword_master() -> None:
    """keyword_master_id 不存在 → 返回 inserted=0。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            tid = str(new_uuid())
            result = await run_fan_out_for_tenant_keyword(conn, tid, str(new_uuid()))
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["inserted"] == 0


# ── hidden 公司重新 fan_out 变 visible ────────────────────────

async def test_fan_out_restores_hidden_to_visible() -> None:
    """之前 hidden 的公司，重新 fan_out 后变为 visible。"""
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _setup_wmt_tables(conn)
            km_id = str(new_uuid())
            tid = str(new_uuid())
            await _insert_km(conn, km_id, "PCB")
            wmt_id = await _insert_wmt_clean(conn, company_name="Restore Co", km_ids=[km_id])
            await _subscribe(conn, tid, km_id)

            await conn.execute(
                text("""
                    INSERT INTO tenant_companies (tenant_id, clean_company_id, visibility_status)
                    VALUES (:tid, :cid, 'hidden')
                """),
                {"tid": tid, "cid": wmt_id},
            )

            result = await run_fan_out_for_tenant_keyword(conn, tid, km_id)
            status = (await conn.execute(
                text("SELECT visibility_status FROM tenant_companies WHERE tenant_id = :tid AND clean_company_id = :cid"),
                {"tid": tid, "cid": wmt_id},
            )).scalar_one()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["inserted"] == 1
    assert status == "visible"
