from uuid import uuid4

from sqlalchemy import text

from app.core.ids import new_uuid
from app.workers.fan_out import run_fan_out_for_tenant_keyword
from tests.helpers import make_engine


async def test_slice2_shared_company_dedup_keeps_tenant_private_state_isolated() -> None:
    engine = make_engine()
    try:
        async with engine.begin() as conn:
            tenant_a = str(new_uuid())
            tenant_b = str(new_uuid())
            normalized_name = f"shared-pcb-buyer-{uuid4().hex}"
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE keyword_master (
                      id uuid PRIMARY KEY,
                      keyword text NOT NULL,
                      keyword_normalized text NOT NULL UNIQUE
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE tenant_keyword (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      tenant_id uuid NOT NULL,
                      keyword_master_id uuid NOT NULL,
                      keyword_raw text NOT NULL,
                      created_by uuid,
                      created_at timestamptz NOT NULL DEFAULT now(),
                      status text NOT NULL DEFAULT 'active',
                      UNIQUE (tenant_id, keyword_master_id)
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE clean_companies (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name text NOT NULL,
                      name_normalized text NOT NULL,
                      country_iso3 char(3) NOT NULL,
                      website text,
                      industry_desc text,
                      product_tags text[] DEFAULT '{}',
                      pcb_suppliers text[] DEFAULT '{}',
                      UNIQUE (name_normalized, country_iso3)
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE clean_company_keywords (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      clean_company_id bigint NOT NULL,
                      keyword_master_id uuid NOT NULL,
                      UNIQUE (clean_company_id, keyword_master_id)
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE clean_contacts (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      clean_company_id bigint NOT NULL
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE tenant_companies (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      tenant_id uuid NOT NULL,
                      clean_company_id bigint NOT NULL,
                      business_status text NOT NULL DEFAULT 'new',
                      data_status text NOT NULL DEFAULT 'ready',
                      visibility_status text NOT NULL DEFAULT 'hidden',
                      model_score numeric,
                      score numeric,
                      note text,
                      tags text[] DEFAULT '{}',
                      updated_at timestamptz NOT NULL DEFAULT now(),
                      UNIQUE (tenant_id, clean_company_id)
                    ) ON COMMIT DROP
                    """
                )
            )

            clean_company_id = (
                await conn.execute(
                    text(
                        """
                        INSERT INTO clean_companies (name, name_normalized, country_iso3)
                        VALUES (:name, :name_normalized, 'USA')
                        ON CONFLICT (name_normalized, country_iso3) DO UPDATE
                        SET name = EXCLUDED.name
                        RETURNING id
                        """
                    ),
                    {
                        "name": "Shared PCB Buyer",
                        "name_normalized": normalized_name,
                    },
                )
            ).scalar_one()
            dedup_company_id = (
                await conn.execute(
                    text(
                        """
                        INSERT INTO clean_companies (name, name_normalized, country_iso3)
                        VALUES (:name, :name_normalized, 'USA')
                        ON CONFLICT (name_normalized, country_iso3) DO UPDATE
                        SET name = EXCLUDED.name
                        RETURNING id
                        """
                    ),
                    {
                        "name": "Shared PCB Buyer Updated",
                        "name_normalized": normalized_name,
                    },
                )
            ).scalar_one()
            assert clean_company_id == dedup_company_id

            await conn.execute(
                text(
                    """
                    INSERT INTO tenant_companies
                      (tenant_id, clean_company_id, business_status, data_status, score, note, tags)
                    VALUES
                      (:tenant_a, :clean_company_id, 'selected', 'ready', 91, 'A private note', ARRAY['a-hot']),
                      (:tenant_b, :clean_company_id, 'new', 'missing_contacts', 42, 'B private note', ARRAY['b-cold'])
                    """
                ),
                {
                    "tenant_a": tenant_a,
                    "tenant_b": tenant_b,
                    "clean_company_id": clean_company_id,
                },
            )
            rows = (
                await conn.execute(
                    text(
                        """
                        SELECT tenant_id::text, clean_company_id, business_status, data_status, score, note, tags
                        FROM tenant_companies
                        WHERE clean_company_id = :clean_company_id
                        ORDER BY tenant_id::text
                        """
                    ),
                    {"clean_company_id": clean_company_id},
                )
            ).mappings().all()

        assert len(rows) == 2
        assert {row["clean_company_id"] for row in rows} == {clean_company_id}
        assert {row["note"] for row in rows} == {"A private note", "B private note"}
        assert {row["business_status"] for row in rows} == {"selected", "new"}
    finally:
        await engine.dispose()


async def test_slice2_new_subscriber_gets_existing_keyword_companies_immediately() -> None:
    engine = make_engine()
    try:
        async with engine.begin() as conn:
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE keyword_master (
                      id uuid PRIMARY KEY,
                      keyword text NOT NULL,
                      keyword_normalized text NOT NULL UNIQUE
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE tenant_keyword (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      tenant_id uuid NOT NULL,
                      keyword_master_id uuid NOT NULL,
                      keyword_raw text NOT NULL,
                      created_by uuid,
                      created_at timestamptz NOT NULL DEFAULT now(),
                      status text NOT NULL DEFAULT 'active',
                      UNIQUE (tenant_id, keyword_master_id)
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE clean_companies (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name text NOT NULL,
                      name_normalized text NOT NULL,
                      country_iso3 char(3) NOT NULL,
                      website text,
                      industry_desc text,
                      product_tags text[] DEFAULT '{}',
                      pcb_suppliers text[] DEFAULT '{}',
                      UNIQUE (name_normalized, country_iso3)
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE clean_company_keywords (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      clean_company_id bigint NOT NULL,
                      keyword_master_id uuid NOT NULL,
                      UNIQUE (clean_company_id, keyword_master_id)
                    ) ON COMMIT DROP
                    """
                )
            )
            await conn.execute(
                text(
                    """
                    CREATE TEMP TABLE tenant_companies (
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      tenant_id uuid NOT NULL,
                      clean_company_id bigint NOT NULL,
                      business_status text NOT NULL DEFAULT 'new',
                      data_status text NOT NULL DEFAULT 'ready',
                      visibility_status text NOT NULL DEFAULT 'hidden',
                      model_score numeric,
                      score numeric,
                      note text,
                      tags text[] DEFAULT '{}',
                      updated_at timestamptz NOT NULL DEFAULT now(),
                      UNIQUE (tenant_id, clean_company_id)
                    ) ON COMMIT DROP
                    """
                )
            )

            keyword_master_id = str(new_uuid())
            tenant_a = str(new_uuid())
            tenant_b = str(new_uuid())
            await conn.execute(
                text(
                    """
                    INSERT INTO keyword_master (id, keyword, keyword_normalized)
                    VALUES (:keyword_master_id, 'PCB', 'pcb')
                    """
                ),
                {"keyword_master_id": keyword_master_id},
            )
            clean_company_id = (
                await conn.execute(
                    text(
                        """
                        INSERT INTO clean_companies (name, name_normalized, country_iso3)
                        VALUES (:name, :name_normalized, 'USA')
                        RETURNING id
                        """
                    ),
                    {
                        "name": "Existing PCB Buyer",
                        "name_normalized": f"existing-pcb-buyer-{uuid4().hex}",
                    },
                )
            ).scalar_one()
            await conn.execute(
                text(
                    """
                    INSERT INTO clean_company_keywords (clean_company_id, keyword_master_id)
                    VALUES (:clean_company_id, :keyword_master_id)
                    """
                ),
                {"clean_company_id": clean_company_id, "keyword_master_id": keyword_master_id},
            )
            await conn.execute(
                text(
                    """
                    INSERT INTO tenant_keyword (tenant_id, keyword_master_id, keyword_raw, status)
                    VALUES
                      (:tenant_a, :keyword_master_id, 'PCB', 'active'),
                      (:tenant_b, :keyword_master_id, 'P.C.B', 'active')
                    """
                ),
                {
                    "tenant_a": tenant_a,
                    "tenant_b": tenant_b,
                    "keyword_master_id": keyword_master_id,
                },
            )
            await conn.execute(
                text(
                    """
                    INSERT INTO tenant_companies
                      (tenant_id, clean_company_id, business_status, data_status, score, note, tags)
                    VALUES
                      (:tenant_a, :clean_company_id, 'selected', 'ready', 86, 'A state', ARRAY['owned-by-a'])
                    """
                ),
                {"tenant_a": tenant_a, "clean_company_id": clean_company_id},
            )

            result = await run_fan_out_for_tenant_keyword(
                conn,
                tenant_id=tenant_b,
                keyword_master_id=keyword_master_id,
            )
            rows = (
                await conn.execute(
                    text(
                        """
                        SELECT tenant_id::text, business_status, data_status, score, note, tags
                        FROM tenant_companies
                        WHERE clean_company_id = :clean_company_id
                        ORDER BY tenant_id::text
                        """
                    ),
                    {"clean_company_id": clean_company_id},
                )
            ).mappings().all()

        tenant_b_row = next(row for row in rows if row["tenant_id"] == tenant_b)
        assert result["inserted"] == 1
        assert tenant_b_row["business_status"] == "new"
        assert tenant_b_row["data_status"] == "missing_contacts"
        assert tenant_b_row["score"] is None
        assert tenant_b_row["note"] is None
        assert list(tenant_b_row["tags"] or []) == []
    finally:
        await engine.dispose()
