from sqlalchemy import text

from app.core.ids import new_uuid
from app.workers.fan_out import run_fan_out_for_tenant_keyword
from tests.helpers import make_engine


async def _create_fan_out_temp_tables(conn) -> None:
    statements = [
        """
            CREATE TEMP TABLE keyword_master (
              id uuid PRIMARY KEY,
              keyword text NOT NULL,
              keyword_normalized text NOT NULL UNIQUE
            ) ON COMMIT DROP;
        """,
        """
            CREATE TEMP TABLE clean_companies (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name text,
              name_normalized text NOT NULL,
              country_iso3 char(3),
              website text,
              industry_desc text,
              product_tags text[] DEFAULT '{}',
              pcb_suppliers text[] DEFAULT '{}'
            ) ON COMMIT DROP;
        """,
        """
            CREATE TEMP TABLE clean_company_keywords (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              clean_company_id bigint NOT NULL,
              keyword_master_id uuid NOT NULL,
              UNIQUE (clean_company_id, keyword_master_id)
            ) ON COMMIT DROP;
        """,
        """
            CREATE TEMP TABLE clean_contacts (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              clean_company_id bigint NOT NULL
            ) ON COMMIT DROP;
        """,
        """
            CREATE TEMP TABLE tenant_keyword (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id uuid NOT NULL,
              keyword_master_id uuid NOT NULL,
              keyword_raw text NOT NULL,
              status text NOT NULL DEFAULT 'active',
              UNIQUE (tenant_id, keyword_master_id)
            ) ON COMMIT DROP;
        """,
        """
            CREATE TEMP TABLE tenant_companies (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id uuid NOT NULL,
              clean_company_id bigint NOT NULL,
              business_status text NOT NULL DEFAULT 'new',
              data_status text NOT NULL DEFAULT 'ready',
              visibility_status text NOT NULL DEFAULT 'hidden',
              model_score numeric,
              score numeric,
              note text,
              tags text[] DEFAULT '{}',
              updated_at timestamptz NOT NULL DEFAULT now(),
              UNIQUE (tenant_id, clean_company_id)
            ) ON COMMIT DROP;
        """,
    ]
    for statement in statements:
        await conn.execute(text(statement))


async def test_fan_out_inserts_existing_clean_keyword_companies_for_new_tenant() -> None:
    engine = make_engine()
    async with engine.connect() as conn:
        tx = await conn.begin()
        try:
            await _create_fan_out_temp_tables(conn)
            keyword_master_id = str(new_uuid())
            source_tenant_id = str(new_uuid())
            target_tenant_id = str(new_uuid())
            await conn.execute(
                text(
                    """
                    INSERT INTO keyword_master (id, keyword, keyword_normalized)
                    VALUES (:id, 'P.C.B', 'pcb')
                    """
                ),
                {"id": keyword_master_id},
            )

            clean_company_id = (
                await conn.execute(
                    text(
                        """
                        INSERT INTO clean_companies (name, name_normalized, country_iso3)
                        VALUES (:name, :name_normalized, 'USA')
                        RETURNING id
                        """
                    ),
                    {
                        "name": "Fanout PCB Buyer",
                        "name_normalized": f"fanout-pcb-buyer-{new_uuid()}",
                    },
                )
            ).scalar_one()
            await conn.execute(
                text(
                    """
                    INSERT INTO clean_company_keywords (clean_company_id, keyword_master_id)
                    VALUES (:clean_company_id, :keyword_master_id)
                    """
                ),
                {"clean_company_id": clean_company_id, "keyword_master_id": keyword_master_id},
            )
            await conn.execute(
                text(
                    """
                    INSERT INTO tenant_keyword (tenant_id, keyword_master_id, keyword_raw, status)
                    VALUES
                      (:source_tenant_id, :keyword_master_id, 'PCB', 'active'),
                      (:target_tenant_id, :keyword_master_id, 'P.C.B', 'active')
                    ON CONFLICT (tenant_id, keyword_master_id) DO UPDATE
                    SET status = 'active'
                    """
                ),
                {
                    "source_tenant_id": source_tenant_id,
                    "target_tenant_id": target_tenant_id,
                    "keyword_master_id": keyword_master_id,
                },
            )
            await conn.execute(
                text(
                    """
                    INSERT INTO tenant_companies
                      (tenant_id, clean_company_id, business_status, data_status, model_score, score)
                    VALUES (:tenant_id, :clean_company_id, 'new', 'ready', 82, 82)
                    """
                ),
                {"tenant_id": source_tenant_id, "clean_company_id": clean_company_id},
            )

            result = await run_fan_out_for_tenant_keyword(
                conn,
                tenant_id=target_tenant_id,
                keyword_master_id=str(keyword_master_id),
            )
            second = await run_fan_out_for_tenant_keyword(
                conn,
                tenant_id=target_tenant_id,
                keyword_master_id=str(keyword_master_id),
            )
            target_rows = (
                await conn.execute(
                    text(
                        """
                        SELECT business_status, data_status, model_score, score, note, tags
                        FROM tenant_companies
                        WHERE tenant_id = :tenant_id
                          AND clean_company_id = :clean_company_id
                        """
                    ),
                    {"tenant_id": target_tenant_id, "clean_company_id": clean_company_id},
                )
            ).mappings().all()
        finally:
            await tx.rollback()
            await engine.dispose()

    assert result["inserted"] == 1
    assert second["inserted"] == 0
    assert len(target_rows) == 1
    assert target_rows[0]["business_status"] == "new"
    assert target_rows[0]["data_status"] == "missing_contacts"
    assert target_rows[0]["model_score"] is None
    assert target_rows[0]["score"] is None
    assert target_rows[0]["note"] is None
    assert list(target_rows[0]["tags"] or []) == []
