curl 'https://bizr.tendata.cn/api/contactx/v3/contacts/linkedin?globizCompanyId=MY001229842&userId=79446&companyName=FILTERMATION+MFG+SDN+BHD&website=filtermation-mfg.com&country=MYS&linkedInCompanyId=nordin-technologies&taxNo=515727H&snovioIdentify=&tid=MYSN8fef573bbb52eb4519c1917faa18c1ea&page=0&size=10' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -b '<SAME_COOKIES_AS_DETAIL>; JSESSIONID=<JSESSIONID>' \
  -H 'priority: u=1, i' \
  -H 'referer: https://bizr.tendata.cn/enterprise' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'
