curl 'https://bizr.tendata.cn/api/corp/v2/companies/0?queryType=ALL&tid=INDI6d2d38e51b0338f13b702e9613d9d44e&catalog=BUYER&website=posiflow.in&name=POSIFLOW+RETAIL+PRIVATE+LIMITED&countryCode3=IND&_t=1777529108047' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -b '<SAME_COOKIES_AS_SEARCH>; JSESSIONID=<JSESSIONID>' \
  -H 'priority: u=1, i' \
  -H 'referer: https://bizr.tendata.cn/enterprise' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'
