"""Align provider raw schemas for collection path evidence.

revision: 20260509_0035
down_revision: 20260508_0034
"""

from alembic import op

revision = "20260509_0035"
down_revision = "20260508_0034"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        r"""
        CREATE EXTENSION IF NOT EXISTS citext;

        DO $$
        BEGIN
          IF to_regclass('public.tendata_raw_companies') IS NOT NULL THEN
            ALTER TABLE tendata_raw_companies RENAME TO tendata_raw_companies_0035_old;
          END IF;
        END $$;

        CREATE TABLE tendata_raw_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          keyword_master_id uuid REFERENCES keyword_master(id) ON DELETE SET NULL,
          source_id text NOT NULL,
          collection_type text NOT NULL DEFAULT 'reverse_lookup'
            CHECK (collection_type IN ('direct_search','reverse_lookup')),
          globiz_id text,
          name text,
          name_local text,
          country_iso3 char(3) CHECK (country_iso3 IS NULL OR country_iso3 ~ '^[A-Z]{3}$'),
          website text,
          tax_no text,
          incorporation_date date,
          employee_num text,
          industry_desc text,
          product_tags text[],
          pcb_suppliers text[],
          trade_amount_3y_usd numeric,
          trade_count int,
          contacts_count int,
          has_trade_data boolean,
          aliases text[],
          raw_payload jsonb,
          detail_status text NOT NULL DEFAULT 'pending'
            CHECK (detail_status IN ('pending','fetched','failed','skipped')),
          detail_fetched_at timestamptz,
          trade_status text NOT NULL DEFAULT 'pending'
            CHECK (trade_status IN ('pending','fetched','failed','skipped')),
          trade_fetched_at timestamptz,
          contacts_status text NOT NULL DEFAULT 'pending'
            CHECK (contacts_status IN ('pending','fetched','failed','skipped')),
          contacts_fetched_at timestamptz,
          enrichment_error jsonb,
          created_at timestamptz DEFAULT now(),
          UNIQUE (keyword_master_id, source_id, collection_type)
        );

        DO $$
        DECLARE
          has_old boolean := to_regclass('public.tendata_raw_companies_0035_old') IS NOT NULL;
          has_id boolean;
          has_source_id boolean;
          has_tid boolean;
          has_keyword_master_id boolean;
          has_collection_type boolean;
          has_detail_status boolean;
          has_detail_fetched_at boolean;
          has_trade_status boolean;
          has_trade_fetched_at boolean;
          has_contacts_status boolean;
          has_contacts_fetched_at boolean;
          has_enrichment_error boolean;
        BEGIN
          IF has_old THEN
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='id') INTO has_id;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='source_id') INTO has_source_id;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='tid') INTO has_tid;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='keyword_master_id') INTO has_keyword_master_id;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='collection_type') INTO has_collection_type;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='detail_status') INTO has_detail_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='detail_fetched_at') INTO has_detail_fetched_at;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='trade_status') INTO has_trade_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='trade_fetched_at') INTO has_trade_fetched_at;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='contacts_status') INTO has_contacts_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='contacts_fetched_at') INTO has_contacts_fetched_at;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='tendata_raw_companies_0035_old' AND column_name='enrichment_error') INTO has_enrichment_error;

            EXECUTE format(
              'INSERT INTO tendata_raw_companies (
                 %s keyword_master_id, source_id, collection_type, globiz_id, name, name_local,
                 country_iso3, website, tax_no, incorporation_date, employee_num, industry_desc,
                 product_tags, pcb_suppliers, trade_amount_3y_usd, trade_count, contacts_count,
                 has_trade_data, aliases, raw_payload, detail_status, detail_fetched_at,
                 trade_status, trade_fetched_at, contacts_status, contacts_fetched_at,
                 enrichment_error, created_at
               )
               SELECT %s
                 %s,
                 %s,
                 %s,
                 globiz_id, name, name_local, country_iso3, website, tax_no, incorporation_date,
                 employee_num::text, industry_desc, product_tags, pcb_suppliers,
                 trade_amount_3y_usd, trade_count, contacts_count, has_trade_data, aliases, raw_payload,
                 %s, %s, %s, %s, %s, %s, %s, created_at
               FROM tendata_raw_companies_0035_old
               ON CONFLICT DO NOTHING',
              CASE WHEN has_id THEN 'id,' ELSE '' END,
              CASE WHEN has_id THEN 'id,' ELSE '' END,
              CASE WHEN has_keyword_master_id THEN 'keyword_master_id' ELSE 'NULL::uuid' END,
              CASE WHEN has_source_id THEN 'source_id' ELSE 'tid' END,
              CASE WHEN has_collection_type THEN 'collection_type' ELSE '''reverse_lookup''' END,
              CASE WHEN has_detail_status THEN 'detail_status' ELSE '''pending''' END,
              CASE WHEN has_detail_fetched_at THEN 'detail_fetched_at' ELSE 'NULL::timestamptz' END,
              CASE WHEN has_trade_status THEN 'trade_status' ELSE '''pending''' END,
              CASE WHEN has_trade_fetched_at THEN 'trade_fetched_at' ELSE 'NULL::timestamptz' END,
              CASE WHEN has_contacts_status THEN 'contacts_status' ELSE '''pending''' END,
              CASE WHEN has_contacts_fetched_at THEN 'contacts_fetched_at' ELSE 'NULL::timestamptz' END,
              CASE WHEN has_enrichment_error THEN 'enrichment_error' ELSE 'NULL::jsonb' END
            );
          END IF;
        END $$;

        DROP TABLE IF EXISTS tendata_raw_companies_0035_old CASCADE;
        CREATE INDEX idx_tendata_raw_companies_keyword ON tendata_raw_companies(keyword_master_id);
        CREATE INDEX idx_tendata_raw_companies_source ON tendata_raw_companies(source_id);
        CREATE INDEX idx_tendata_raw_companies_globiz ON tendata_raw_companies(globiz_id) WHERE globiz_id IS NOT NULL;
        CREATE INDEX idx_tendata_raw_companies_country ON tendata_raw_companies(country_iso3);

        DO $$
        BEGIN
          IF to_regclass('public.waimaotong_raw_contacts') IS NOT NULL THEN
            ALTER TABLE waimaotong_raw_contacts RENAME TO waimaotong_raw_contacts_0035_old;
          END IF;
          IF to_regclass('public.waimaotong_raw_companies') IS NOT NULL THEN
            ALTER TABLE waimaotong_raw_companies RENAME TO waimaotong_raw_companies_0035_old;
          END IF;
        END $$;

        CREATE TABLE waimaotong_raw_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          keyword_master_id uuid REFERENCES keyword_master(id) ON DELETE SET NULL,
          collection_type text NOT NULL DEFAULT 'direct_search'
            CHECK (collection_type IN ('direct_search','reverse_lookup')),
          source_id text NOT NULL,
          real_id text,
          name text,
          country_iso3 char(3) CHECK (country_iso3 IS NULL OR country_iso3 ~ '^[A-Z]{3}$'),
          domain text,
          industry text,
          address text,
          phone text,
          employee_size text,
          founded_year int,
          description text,
          products text[],
          source_tags text[],
          emails text[],
          trade_amount_3y_usd numeric,
          trade_count int,
          contacts_count int,
          has_trade_data boolean,
          customs_data jsonb,
          search_payload jsonb,
          detail_payload jsonb,
          trade_payload jsonb,
          raw_payload jsonb,
          detail_status text NOT NULL DEFAULT 'pending'
            CHECK (detail_status IN ('pending','fetched','failed','skipped')),
          detail_fetched_at timestamptz,
          trade_status text NOT NULL DEFAULT 'pending'
            CHECK (trade_status IN ('pending','fetched','failed','skipped')),
          trade_fetched_at timestamptz,
          contacts_status text NOT NULL DEFAULT 'pending'
            CHECK (contacts_status IN ('pending','fetched','failed','skipped')),
          contacts_fetched_at timestamptz,
          enrichment_error jsonb,
          created_at timestamptz DEFAULT now(),
          updated_at timestamptz DEFAULT now(),
          UNIQUE (keyword_master_id, source_id, collection_type)
        );

        DO $$
        DECLARE
          has_old boolean := to_regclass('public.waimaotong_raw_companies_0035_old') IS NOT NULL;
          has_keyword_master_id boolean;
          has_real_id boolean;
          has_address boolean;
          has_employee_size boolean;
          has_founded_year boolean;
          has_description boolean;
          has_products boolean;
          has_source_tags boolean;
          has_trade_amount boolean;
          has_trade_count boolean;
          has_contacts_count boolean;
          has_has_trade_data boolean;
          has_search_payload boolean;
          has_detail_payload boolean;
          has_trade_payload boolean;
          has_detail_status boolean;
          has_detail_fetched_at boolean;
          has_trade_status boolean;
          has_trade_fetched_at boolean;
          has_contacts_status boolean;
          has_contacts_fetched_at boolean;
          has_enrichment_error boolean;
          has_updated_at boolean;
        BEGIN
          IF has_old THEN
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='keyword_master_id') INTO has_keyword_master_id;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='real_id') INTO has_real_id;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='address') INTO has_address;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='employee_size') INTO has_employee_size;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='founded_year') INTO has_founded_year;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='description') INTO has_description;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='products') INTO has_products;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='source_tags') INTO has_source_tags;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='trade_amount_3y_usd') INTO has_trade_amount;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='trade_count') INTO has_trade_count;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='contacts_count') INTO has_contacts_count;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='has_trade_data') INTO has_has_trade_data;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='search_payload') INTO has_search_payload;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='detail_payload') INTO has_detail_payload;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='trade_payload') INTO has_trade_payload;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='detail_status') INTO has_detail_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='detail_fetched_at') INTO has_detail_fetched_at;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='trade_status') INTO has_trade_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='trade_fetched_at') INTO has_trade_fetched_at;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='contacts_status') INTO has_contacts_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='contacts_fetched_at') INTO has_contacts_fetched_at;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='enrichment_error') INTO has_enrichment_error;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_companies_0035_old' AND column_name='updated_at') INTO has_updated_at;

            EXECUTE format(
              'INSERT INTO waimaotong_raw_companies (
                 id, keyword_master_id, collection_type, source_id, real_id, name, country_iso3,
                 domain, industry, address, phone, employee_size, founded_year, description,
                 products, source_tags, emails, trade_amount_3y_usd, trade_count, contacts_count,
                 has_trade_data, customs_data, search_payload, detail_payload, trade_payload,
                 raw_payload, detail_status, detail_fetched_at, trade_status, trade_fetched_at,
                 contacts_status, contacts_fetched_at, enrichment_error, created_at, updated_at
               )
               SELECT id,
                 %s, collection_type, source_id, %s, name, country_iso3, domain, industry,
                 %s, phone, %s, %s, %s, %s, %s, emails, %s, %s, %s, %s, customs_data,
                 %s, %s, %s, raw_payload, %s, %s, %s, %s, %s, %s, %s, created_at, %s
               FROM waimaotong_raw_companies_0035_old
               ON CONFLICT DO NOTHING',
              CASE WHEN has_keyword_master_id THEN 'keyword_master_id' ELSE 'NULL::uuid' END,
              CASE WHEN has_real_id THEN 'real_id' ELSE 'NULL::text' END,
              CASE WHEN has_address THEN 'address' ELSE 'NULL::text' END,
              CASE WHEN has_employee_size THEN 'employee_size' ELSE 'NULL::text' END,
              CASE WHEN has_founded_year THEN 'founded_year' ELSE 'NULL::int' END,
              CASE WHEN has_description THEN 'description' ELSE 'NULL::text' END,
              CASE WHEN has_products THEN 'products' ELSE 'NULL::text[]' END,
              CASE WHEN has_source_tags THEN 'source_tags' ELSE 'NULL::text[]' END,
              CASE WHEN has_trade_amount THEN 'trade_amount_3y_usd' ELSE 'NULL::numeric' END,
              CASE WHEN has_trade_count THEN 'trade_count' ELSE 'NULL::int' END,
              CASE WHEN has_contacts_count THEN 'contacts_count' ELSE 'NULL::int' END,
              CASE WHEN has_has_trade_data THEN 'has_trade_data' ELSE 'NULL::boolean' END,
              CASE WHEN has_search_payload THEN 'search_payload' ELSE 'raw_payload' END,
              CASE WHEN has_detail_payload THEN 'detail_payload' ELSE 'NULL::jsonb' END,
              CASE WHEN has_trade_payload THEN 'trade_payload' ELSE 'customs_data' END,
              CASE WHEN has_detail_status THEN 'detail_status' ELSE '''pending''' END,
              CASE WHEN has_detail_fetched_at THEN 'detail_fetched_at' ELSE 'NULL::timestamptz' END,
              CASE WHEN has_trade_status THEN 'trade_status' ELSE '''pending''' END,
              CASE WHEN has_trade_fetched_at THEN 'trade_fetched_at' ELSE 'NULL::timestamptz' END,
              CASE WHEN has_contacts_status THEN 'contacts_status' ELSE '''pending''' END,
              CASE WHEN has_contacts_fetched_at THEN 'contacts_fetched_at' ELSE 'NULL::timestamptz' END,
              CASE WHEN has_enrichment_error THEN 'enrichment_error' ELSE 'NULL::jsonb' END,
              CASE WHEN has_updated_at THEN 'updated_at' ELSE 'created_at' END
            );
          END IF;
        END $$;

        INSERT INTO waimaotong_raw_companies (source_id, collection_type, name, raw_payload)
        SELECT DISTINCT source_company_id, 'direct_search', source_company_id, '{}'::jsonb
        FROM waimaotong_raw_contacts_0035_old old
        WHERE to_regclass('public.waimaotong_raw_contacts_0035_old') IS NOT NULL
          AND NOT EXISTS (
            SELECT 1
            FROM waimaotong_raw_companies c
            WHERE c.source_id = old.source_company_id
              AND c.collection_type = 'direct_search'
          );

        CREATE INDEX idx_wmt_raw_companies_keyword ON waimaotong_raw_companies(keyword_master_id);
        CREATE INDEX idx_wmt_raw_companies_source ON waimaotong_raw_companies(source_id);

        CREATE TABLE waimaotong_raw_contacts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          raw_company_id bigint NOT NULL REFERENCES waimaotong_raw_companies(id) ON DELETE CASCADE,
          source_contact_id text,
          name text,
          position text,
          department text,
          email citext,
          email_status text,
          phone text,
          mobile text,
          linkedin text,
          whatsapp text,
          source text,
          confidence numeric,
          raw_payload jsonb,
          created_at timestamptz DEFAULT now()
        );

        DO $$
        DECLARE
          has_old boolean := to_regclass('public.waimaotong_raw_contacts_0035_old') IS NOT NULL;
          has_raw_company_id boolean;
          has_position boolean;
          has_title boolean;
          has_department boolean;
          has_email_status boolean;
          has_mobile boolean;
          has_linkedin boolean;
          has_whatsapp boolean;
          has_source boolean;
          has_confidence boolean;
        BEGIN
          IF has_old THEN
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='raw_company_id') INTO has_raw_company_id;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='position') INTO has_position;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='title') INTO has_title;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='department') INTO has_department;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='email_status') INTO has_email_status;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='mobile') INTO has_mobile;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='linkedin') INTO has_linkedin;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='whatsapp') INTO has_whatsapp;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='source') INTO has_source;
            SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='waimaotong_raw_contacts_0035_old' AND column_name='confidence') INTO has_confidence;

            IF has_raw_company_id THEN
              EXECUTE format(
                'INSERT INTO waimaotong_raw_contacts (
                   id, raw_company_id, source_contact_id, name, position, department, email,
                   email_status, phone, mobile, linkedin, whatsapp, source, confidence,
                   raw_payload, created_at
                 )
                 SELECT id, raw_company_id, source_contact_id, name, %s, %s, email::citext,
                        %s, phone, %s, %s, %s, %s, %s, raw_payload, created_at
                 FROM waimaotong_raw_contacts_0035_old
                 WHERE raw_company_id IS NOT NULL',
                CASE WHEN has_position THEN 'position' WHEN has_title THEN 'title' ELSE 'NULL::text' END,
                CASE WHEN has_department THEN 'department' ELSE 'NULL::text' END,
                CASE WHEN has_email_status THEN 'email_status' ELSE 'NULL::text' END,
                CASE WHEN has_mobile THEN 'mobile' ELSE 'NULL::text' END,
                CASE WHEN has_linkedin THEN 'linkedin' ELSE 'NULL::text' END,
                CASE WHEN has_whatsapp THEN 'whatsapp' ELSE 'NULL::text' END,
                CASE WHEN has_source THEN 'source' ELSE 'NULL::text' END,
                CASE WHEN has_confidence THEN 'confidence' ELSE 'NULL::numeric' END
              );
            ELSE
              EXECUTE format(
                'INSERT INTO waimaotong_raw_contacts (
                   id, raw_company_id, source_contact_id, name, position, department, email,
                   email_status, phone, mobile, linkedin, whatsapp, source, confidence,
                   raw_payload, created_at
                 )
                 SELECT old.id, c.id, old.source_contact_id, old.name, %s, %s, old.email::citext,
                        %s, old.phone, %s, %s, %s, %s, %s, old.raw_payload, old.created_at
                 FROM waimaotong_raw_contacts_0035_old old
                 JOIN waimaotong_raw_companies c
                   ON c.source_id = old.source_company_id
                  AND c.collection_type = ''direct_search''',
                CASE WHEN has_position THEN 'old.position' WHEN has_title THEN 'old.title' ELSE 'NULL::text' END,
                CASE WHEN has_department THEN 'old.department' ELSE 'NULL::text' END,
                CASE WHEN has_email_status THEN 'old.email_status' ELSE 'NULL::text' END,
                CASE WHEN has_mobile THEN 'old.mobile' ELSE 'NULL::text' END,
                CASE WHEN has_linkedin THEN 'old.linkedin' ELSE 'NULL::text' END,
                CASE WHEN has_whatsapp THEN 'old.whatsapp' ELSE 'NULL::text' END,
                CASE WHEN has_source THEN 'old.source' ELSE 'NULL::text' END,
                CASE WHEN has_confidence THEN 'old.confidence' ELSE 'NULL::numeric' END
              );
            END IF;
          END IF;
        END $$;

        DROP TABLE IF EXISTS waimaotong_raw_contacts_0035_old;
        DROP TABLE IF EXISTS waimaotong_raw_companies_0035_old CASCADE;
        CREATE INDEX idx_wmt_raw_contacts_company ON waimaotong_raw_contacts(raw_company_id);
        CREATE UNIQUE INDEX uq_wmt_raw_contacts_source_contact
          ON waimaotong_raw_contacts(raw_company_id, source_contact_id)
          WHERE source_contact_id IS NOT NULL;
        CREATE UNIQUE INDEX uq_wmt_raw_contacts_email_fallback
          ON waimaotong_raw_contacts(raw_company_id, email)
          WHERE source_contact_id IS NULL AND email IS NOT NULL;
        CREATE INDEX idx_wmt_raw_contacts_email
          ON waimaotong_raw_contacts(email)
          WHERE email IS NOT NULL;

        SELECT setval(
          pg_get_serial_sequence('tendata_raw_companies', 'id'),
          COALESCE((SELECT MAX(id) FROM tendata_raw_companies), 1),
          (SELECT MAX(id) IS NOT NULL FROM tendata_raw_companies)
        );
        SELECT setval(
          pg_get_serial_sequence('waimaotong_raw_companies', 'id'),
          COALESCE((SELECT MAX(id) FROM waimaotong_raw_companies), 1),
          (SELECT MAX(id) IS NOT NULL FROM waimaotong_raw_companies)
        );
        SELECT setval(
          pg_get_serial_sequence('waimaotong_raw_contacts', 'id'),
          COALESCE((SELECT MAX(id) FROM waimaotong_raw_contacts), 1),
          (SELECT MAX(id) IS NOT NULL FROM waimaotong_raw_contacts)
        );

        DO $$
        BEGIN
          IF to_regclass('public.clean_company_sources') IS NOT NULL THEN
            ALTER TABLE clean_company_sources
              DROP CONSTRAINT IF EXISTS clean_company_sources_source_type_check;
            ALTER TABLE clean_company_sources
              ADD CONSTRAINT clean_company_sources_source_type_check
              CHECK (source_type IN ('tendata','waimaotong'));
          END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.execute(
        r"""
        DO $$
        BEGIN
          IF to_regclass('public.clean_company_sources') IS NOT NULL THEN
            ALTER TABLE clean_company_sources
              DROP CONSTRAINT IF EXISTS clean_company_sources_source_type_check;
            ALTER TABLE clean_company_sources
              ADD CONSTRAINT clean_company_sources_source_type_check
              CHECK (source_type IN ('tendata'));
          END IF;
        END $$;

        DROP TABLE IF EXISTS waimaotong_raw_contacts CASCADE;
        DROP TABLE IF EXISTS waimaotong_raw_companies CASCADE;
        DROP TABLE IF EXISTS tendata_raw_companies CASCADE;
        """
    )
