"""V3 data foundation forward alignment.

revision: 20260508_0034
down_revision: 20260508_0033
"""

from alembic import op

revision = "20260508_0034"
down_revision = "20260508_0033"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE EXTENSION IF NOT EXISTS citext;

        -- tenant_keyword: 0016 已落库为 uuid PK；V3 确认为 bigint + 原始输入 + soft delete。
        DROP TABLE IF EXISTS tenant_keyword_v3;
        CREATE TABLE tenant_keyword_v3 (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
          keyword_master_id uuid NOT NULL REFERENCES keyword_master(id) ON DELETE CASCADE,
          keyword_raw text NOT NULL,
          created_by uuid REFERENCES users(id) ON DELETE SET NULL,
          created_at timestamptz NOT NULL DEFAULT now(),
          status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','deleted')),
          UNIQUE (tenant_id, keyword_master_id)
        );

        INSERT INTO tenant_keyword_v3 (tenant_id, keyword_master_id, keyword_raw, created_by, created_at, status)
        SELECT DISTINCT ON (tk.tenant_id, tk.keyword_master_id)
          tk.tenant_id,
          tk.keyword_master_id,
          COALESCE(ck.keyword, km.keyword) AS keyword_raw,
          ck.created_by,
          COALESCE(tk.created_at, ck.created_at, now()) AS created_at,
          CASE WHEN ck.status = 'deleted' THEN 'deleted' ELSE 'active' END AS status
        FROM tenant_keyword tk
        JOIN keyword_master km ON km.id = tk.keyword_master_id
        LEFT JOIN collection_keywords ck
          ON ck.tenant_id = tk.tenant_id
         AND ck.keyword_master_id = tk.keyword_master_id
        ORDER BY tk.tenant_id, tk.keyword_master_id, COALESCE(tk.created_at, ck.created_at, now()) ASC;

        DROP TABLE IF EXISTS tenant_keyword CASCADE;
        ALTER TABLE tenant_keyword_v3 RENAME TO tenant_keyword;
        CREATE INDEX idx_tenant_keyword_tenant_status ON tenant_keyword(tenant_id, status);
        CREATE INDEX idx_tenant_keyword_master ON tenant_keyword(keyword_master_id);

        -- lixiaoyun raw companies: preserve existing rows; remove task/run-time fields from raw truth.
        ALTER TABLE lixiaoyun_raw_companies
          DROP CONSTRAINT IF EXISTS lixiaoyun_raw_companies_task_id_fkey,
          DROP CONSTRAINT IF EXISTS lixiaoyun_raw_companies_source_id_key,
          ADD COLUMN IF NOT EXISTS keyword_master_id uuid REFERENCES keyword_master(id) ON DELETE SET NULL;
        ALTER TABLE lixiaoyun_raw_companies
          DROP COLUMN IF EXISTS task_id,
          DROP COLUMN IF EXISTS last_seen_at;
        CREATE UNIQUE INDEX IF NOT EXISTS uq_lxy_raw_companies_keyword_source
          ON lixiaoyun_raw_companies(keyword_master_id, source_id);
        CREATE INDEX IF NOT EXISTS idx_lxy_raw_companies_keyword
          ON lixiaoyun_raw_companies(keyword_master_id);
        CREATE INDEX IF NOT EXISTS idx_lxy_raw_companies_source
          ON lixiaoyun_raw_companies(source_id);

        -- tendata raw companies: rebuild to bigint PK + source_id while preserving rows when any exist.
        ALTER TABLE tendata_raw_companies RENAME TO tendata_raw_companies_old;
        CREATE TABLE tendata_raw_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          keyword_master_id uuid REFERENCES keyword_master(id) ON DELETE SET NULL,
          source_id text NOT NULL,
          globiz_id text,
          name text,
          name_local text,
          country_iso3 char(3) CHECK (country_iso3 IS NULL OR country_iso3 ~ '^[A-Z]{3}$'),
          website text,
          tax_no text,
          incorporation_date date,
          employee_num text,
          industry_desc text,
          product_tags text[],
          pcb_suppliers text[],
          trade_amount_3y_usd numeric,
          trade_count int,
          contacts_count int,
          has_trade_data boolean,
          aliases text[],
          raw_payload jsonb,
          created_at timestamptz DEFAULT now(),
          UNIQUE (keyword_master_id, source_id)
        );
        INSERT INTO tendata_raw_companies (
          source_id, globiz_id, name, name_local, country_iso3, website, tax_no,
          incorporation_date, employee_num, industry_desc, product_tags, pcb_suppliers,
          trade_amount_3y_usd, trade_count, contacts_count, has_trade_data, aliases,
          raw_payload, created_at
        )
        SELECT
          tid, globiz_id, name, name_local, country_iso3, website, tax_no,
          incorporation_date, employee_num::text, industry_desc, product_tags, pcb_suppliers,
          trade_amount_3y_usd, trade_count, contacts_count, has_trade_data, aliases,
          raw_payload, created_at
        FROM tendata_raw_companies_old
        ON CONFLICT DO NOTHING;
        DROP TABLE tendata_raw_companies_old;
        CREATE INDEX idx_tendata_raw_companies_keyword ON tendata_raw_companies(keyword_master_id);
        CREATE INDEX idx_tendata_raw_companies_source ON tendata_raw_companies(source_id);
        CREATE INDEX idx_tendata_raw_companies_globiz ON tendata_raw_companies(globiz_id) WHERE globiz_id IS NOT NULL;
        CREATE INDEX idx_tendata_raw_companies_country ON tendata_raw_companies(country_iso3);

        CREATE TABLE IF NOT EXISTS lixiaoyun_raw_contacts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          raw_company_id bigint NOT NULL REFERENCES lixiaoyun_raw_companies(id) ON DELETE CASCADE,
          source_contact_id text,
          name text,
          position text,
          email citext,
          phone text,
          raw_payload jsonb,
          created_at timestamptz DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS idx_lxy_raw_contacts_company ON lixiaoyun_raw_contacts(raw_company_id);
        CREATE UNIQUE INDEX IF NOT EXISTS uq_lxy_raw_contacts_source_contact
          ON lixiaoyun_raw_contacts(raw_company_id, source_contact_id)
          WHERE source_contact_id IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS uq_lxy_raw_contacts_email_fallback
          ON lixiaoyun_raw_contacts(raw_company_id, email)
          WHERE source_contact_id IS NULL AND email IS NOT NULL;
        CREATE INDEX IF NOT EXISTS idx_lxy_raw_contacts_email
          ON lixiaoyun_raw_contacts(email)
          WHERE email IS NOT NULL;

        CREATE TABLE IF NOT EXISTS tendata_raw_contacts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          raw_company_id bigint NOT NULL REFERENCES tendata_raw_companies(id) ON DELETE CASCADE,
          source_contact_id text,
          name text,
          position text,
          email citext,
          phone text,
          raw_payload jsonb,
          created_at timestamptz DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS idx_tendata_raw_contacts_company ON tendata_raw_contacts(raw_company_id);
        CREATE UNIQUE INDEX IF NOT EXISTS uq_tendata_raw_contacts_source_contact
          ON tendata_raw_contacts(raw_company_id, source_contact_id)
          WHERE source_contact_id IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS uq_tendata_raw_contacts_email_fallback
          ON tendata_raw_contacts(raw_company_id, email)
          WHERE source_contact_id IS NULL AND email IS NOT NULL;
        CREATE INDEX IF NOT EXISTS idx_tendata_raw_contacts_email
          ON tendata_raw_contacts(email)
          WHERE email IS NOT NULL;
        """
    )

    op.execute(
        """
        -- These V3 tables are empty in the target business DB at 0032. Rebuild them to the confirmed schema.
        DROP TABLE IF EXISTS clean_company_keywords CASCADE;
        DROP TABLE IF EXISTS clean_company_sources CASCADE;
        DROP TABLE IF EXISTS tenant_contacts CASCADE;
        DROP TABLE IF EXISTS clean_contacts CASCADE;
        DROP TABLE IF EXISTS tenant_companies CASCADE;
        DROP TABLE IF EXISTS clean_companies CASCADE;

        CREATE TABLE clean_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text,
          name_normalized text NOT NULL,
          country_iso3 char(3) CHECK (country_iso3 IS NULL OR country_iso3 ~ '^[A-Z]{3}$'),
          website text,
          tax_no text,
          incorporation_date date,
          reg_capital numeric,
          employee_num text,
          industry_desc text,
          industry_tags text[] DEFAULT '{}',
          product_tags text[] DEFAULT '{}',
          pcb_suppliers text[] DEFAULT '{}',
          trade_amount_3y_usd numeric,
          trade_count int,
          contacts_count int DEFAULT 0,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (name_normalized, country_iso3)
        );
        CREATE INDEX idx_clean_companies_country ON clean_companies(country_iso3);
        CREATE INDEX idx_clean_companies_incorporation_date ON clean_companies(incorporation_date);
        CREATE INDEX idx_clean_companies_reg_capital ON clean_companies(reg_capital);
        CREATE INDEX idx_clean_companies_industry_tags ON clean_companies USING gin(industry_tags);
        CREATE INDEX idx_clean_companies_product_tags ON clean_companies USING gin(product_tags);
        CREATE INDEX idx_clean_companies_employee_num ON clean_companies(employee_num);
        CREATE INDEX idx_clean_companies_trade_amount ON clean_companies(trade_amount_3y_usd);
        CREATE INDEX idx_clean_companies_trade_count ON clean_companies(trade_count);
        CREATE INDEX idx_clean_companies_contacts_count ON clean_companies(contacts_count);
        DROP TRIGGER IF EXISTS set_updated_at ON clean_companies;
        CREATE TRIGGER set_updated_at
          BEFORE UPDATE ON clean_companies
          FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

        CREATE TABLE clean_contacts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          clean_company_id bigint NOT NULL REFERENCES clean_companies(id) ON DELETE CASCADE,
          name text,
          position text,
          email citext,
          phone text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_clean_contacts_company ON clean_contacts(clean_company_id);
        CREATE UNIQUE INDEX uq_clean_contacts_company_email
          ON clean_contacts(clean_company_id, email)
          WHERE email IS NOT NULL;
        CREATE INDEX idx_clean_contacts_email ON clean_contacts(email) WHERE email IS NOT NULL;
        DROP TRIGGER IF EXISTS set_updated_at ON clean_contacts;
        CREATE TRIGGER set_updated_at
          BEFORE UPDATE ON clean_contacts
          FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

        CREATE TABLE clean_company_sources (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          clean_company_id bigint NOT NULL REFERENCES clean_companies(id) ON DELETE CASCADE,
          source_type text NOT NULL CHECK (source_type IN ('tendata')),
          source_company_id bigint NOT NULL,
          source_key text,
          created_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (source_type, source_company_id)
        );
        CREATE INDEX idx_clean_company_sources_company ON clean_company_sources(clean_company_id);
        CREATE INDEX idx_clean_company_sources_type ON clean_company_sources(source_type);

        CREATE TABLE clean_company_keywords (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          clean_company_id bigint NOT NULL REFERENCES clean_companies(id) ON DELETE CASCADE,
          keyword_master_id uuid NOT NULL REFERENCES keyword_master(id) ON DELETE CASCADE,
          created_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (clean_company_id, keyword_master_id)
        );
        CREATE INDEX idx_clean_company_keywords_keyword ON clean_company_keywords(keyword_master_id);

        CREATE TABLE tenant_companies (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
          clean_company_id bigint NOT NULL REFERENCES clean_companies(id) ON DELETE CASCADE,
          business_status text NOT NULL DEFAULT 'new'
            CHECK (business_status IN ('new','selected','in_plan','contacted','archived')),
          data_status text NOT NULL DEFAULT 'ready'
            CHECK (data_status IN ('ready','missing_contacts','insufficient_data')),
          model_score numeric,
          score numeric,
          note text,
          tags text[] DEFAULT '{}',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (tenant_id, clean_company_id)
        );
        CREATE INDEX idx_tenant_companies_tenant_business_status ON tenant_companies(tenant_id, business_status);
        CREATE INDEX idx_tenant_companies_tenant_data_status ON tenant_companies(tenant_id, data_status);
        CREATE INDEX idx_tenant_companies_tenant_score ON tenant_companies(tenant_id, score);
        CREATE INDEX idx_tenant_companies_tags ON tenant_companies USING gin(tags);
        DROP TRIGGER IF EXISTS set_updated_at ON tenant_companies;
        CREATE TRIGGER set_updated_at
          BEFORE UPDATE ON tenant_companies
          FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
        ALTER TABLE tenant_companies ENABLE ROW LEVEL SECURITY;
        CREATE POLICY tenant_select_companies ON tenant_companies
          FOR SELECT USING (tenant_id = current_tenant_id());
        CREATE POLICY tenant_write_companies ON tenant_companies
          FOR ALL USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());

        CREATE TABLE tenant_contacts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
          clean_contact_id bigint NOT NULL REFERENCES clean_contacts(id) ON DELETE CASCADE,
          clean_company_id bigint NOT NULL REFERENCES clean_companies(id) ON DELETE CASCADE,
          contact_status text NOT NULL DEFAULT 'available',
          is_sendable boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (tenant_id, clean_contact_id)
        );
        CREATE INDEX idx_tenant_contacts_tenant_company ON tenant_contacts(tenant_id, clean_company_id);
        CREATE INDEX idx_tenant_contacts_tenant_status ON tenant_contacts(tenant_id, contact_status);
        CREATE INDEX idx_tenant_contacts_tenant_sendable ON tenant_contacts(tenant_id, is_sendable);
        DROP TRIGGER IF EXISTS set_updated_at ON tenant_contacts;
        CREATE TRIGGER set_updated_at
          BEFORE UPDATE ON tenant_contacts
          FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
        """
    )

    op.execute(
        """
        -- Align collection_runs for databases that already executed the old 0033 locally.
        DO $$
        DECLARE
          id_type text;
          run_id_type text;
        BEGIN
          SELECT data_type INTO id_type
          FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = 'collection_runs' AND column_name = 'id';

          IF id_type IS DISTINCT FROM 'bigint' THEN
            ALTER TABLE collection_tasks DROP CONSTRAINT IF EXISTS collection_tasks_run_id_fkey;
            ALTER TABLE collection_tasks DROP COLUMN IF EXISTS run_id;
            DROP TABLE IF EXISTS collection_runs CASCADE;

            CREATE TABLE collection_runs (
              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              keyword_master_id uuid REFERENCES keyword_master(id) ON DELETE SET NULL,
              provider text NOT NULL CHECK (provider IN ('lixiaoyun', 'tendata')),
              stage text NOT NULL CHECK (stage IN ('lixiaoyun_competitors', 'tendata_customers')),
              status text NOT NULL DEFAULT 'not_started'
                CHECK (status IN ('not_started','running','daily_limit_reached','completed','stopped','failed')),
              CHECK (
                (provider = 'lixiaoyun' AND stage = 'lixiaoyun_competitors')
                OR
                (provider = 'tendata' AND stage = 'tendata_customers')
              ),
              daily_limit int NOT NULL DEFAULT 1000,
              request_page_size int NOT NULL DEFAULT 10 CHECK (request_page_size > 0 AND request_page_size <= 100),
              cursor jsonb NOT NULL DEFAULT '{}'::jsonb,
              skip_source_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
              total_fetched int NOT NULL DEFAULT 0,
              today_fetched int NOT NULL DEFAULT 0,
              biz_date date NOT NULL DEFAULT ((now() AT TIME ZONE 'Asia/Shanghai')::date),
              next_run_at timestamptz,
              manual_stopped_at timestamptz,
              completed_at timestamptz,
              error_message text,
              triggered_by uuid REFERENCES users(id) ON DELETE SET NULL,
              triggered_tenant_id uuid REFERENCES tenants(id) ON DELETE SET NULL,
              created_at timestamptz NOT NULL DEFAULT now(),
              updated_at timestamptz NOT NULL DEFAULT now()
            );
            DROP TRIGGER IF EXISTS set_updated_at ON collection_runs;
            CREATE TRIGGER set_updated_at
              BEFORE UPDATE ON collection_runs
              FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
          END IF;

          SELECT data_type INTO run_id_type
          FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = 'collection_tasks' AND column_name = 'run_id';

          IF run_id_type IS DISTINCT FROM 'bigint' THEN
            ALTER TABLE collection_tasks DROP CONSTRAINT IF EXISTS collection_tasks_run_id_fkey;
            ALTER TABLE collection_tasks DROP COLUMN IF EXISTS run_id;
            ALTER TABLE collection_tasks ADD COLUMN run_id bigint REFERENCES collection_runs(id) ON DELETE SET NULL;
          END IF;
        END $$;

        ALTER TABLE collection_tasks
          ADD COLUMN IF NOT EXISTS scheduled_biz_date date,
          ADD COLUMN IF NOT EXISTS batch_no int NOT NULL DEFAULT 1,
          ADD COLUMN IF NOT EXISTS page_size int NOT NULL DEFAULT 10,
          ADD COLUMN IF NOT EXISTS cursor_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

        DROP INDEX IF EXISTS idx_collection_runs_keyword;
        DROP INDEX IF EXISTS idx_collection_runs_keyword_stage_status;
        DROP INDEX IF EXISTS idx_collection_runs_resume;
        DROP INDEX IF EXISTS idx_collection_runs_triggered_tenant;
        DROP INDEX IF EXISTS uq_collection_runs_active;
        CREATE INDEX idx_collection_runs_keyword_stage_status
          ON collection_runs(keyword_master_id, provider, stage, status);
        CREATE INDEX idx_collection_runs_resume
          ON collection_runs(next_run_at)
          WHERE status = 'daily_limit_reached';
        CREATE INDEX idx_collection_runs_triggered_tenant
          ON collection_runs(triggered_tenant_id)
          WHERE triggered_tenant_id IS NOT NULL;
        CREATE UNIQUE INDEX uq_collection_runs_active
          ON collection_runs(keyword_master_id, provider, stage)
          WHERE status IN ('not_started','running','daily_limit_reached');

        DROP INDEX IF EXISTS idx_collection_tasks_run_status;
        DROP INDEX IF EXISTS idx_collection_tasks_run_status_scheduled;
        DROP INDEX IF EXISTS idx_collection_tasks_run;
        CREATE INDEX idx_collection_tasks_run ON collection_tasks(run_id);
        CREATE INDEX idx_collection_tasks_run_status_scheduled
          ON collection_tasks(run_id, status, scheduled_at);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP INDEX IF EXISTS idx_collection_tasks_run_status_scheduled;
        DROP INDEX IF EXISTS idx_collection_tasks_run;
        DROP INDEX IF EXISTS uq_collection_runs_active;
        DROP INDEX IF EXISTS idx_collection_runs_triggered_tenant;
        DROP INDEX IF EXISTS idx_collection_runs_resume;
        DROP INDEX IF EXISTS idx_collection_runs_keyword_stage_status;

        DROP TABLE IF EXISTS tenant_contacts CASCADE;
        DROP TABLE IF EXISTS tenant_companies CASCADE;
        DROP TABLE IF EXISTS clean_company_keywords CASCADE;
        DROP TABLE IF EXISTS clean_company_sources CASCADE;
        DROP TABLE IF EXISTS clean_contacts CASCADE;
        DROP TABLE IF EXISTS clean_companies CASCADE;
        DROP TABLE IF EXISTS tendata_raw_contacts CASCADE;
        DROP TABLE IF EXISTS lixiaoyun_raw_contacts CASCADE;
        """
    )
