"""新增 collection_runs 并让 collection_tasks 关联采集轮次。

revision: 20260508_0033
down_revision: 20260507_0032
"""

from alembic import op

revision = "20260508_0033"
down_revision = "20260507_0032"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS collection_runs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          keyword_master_id uuid REFERENCES keyword_master(id) ON DELETE SET NULL,
          provider text NOT NULL
            CHECK (provider IN ('lixiaoyun', 'tendata')),
          stage text NOT NULL
            CHECK (stage IN ('lixiaoyun_competitors', 'tendata_customers')),
          status text NOT NULL DEFAULT 'not_started'
            CHECK (status IN (
              'not_started','running','daily_limit_reached','completed','stopped','failed'
            )),
          CHECK (
            (provider = 'lixiaoyun' AND stage = 'lixiaoyun_competitors')
            OR
            (provider = 'tendata' AND stage = 'tendata_customers')
          ),
          daily_limit int NOT NULL DEFAULT 1000,
          request_page_size int NOT NULL DEFAULT 10 CHECK (request_page_size > 0 AND request_page_size <= 100),
          cursor jsonb NOT NULL DEFAULT '{}'::jsonb,
          skip_source_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
          total_fetched int NOT NULL DEFAULT 0,
          today_fetched int NOT NULL DEFAULT 0,
          biz_date date NOT NULL DEFAULT ((now() AT TIME ZONE 'Asia/Shanghai')::date),
          next_run_at timestamptz,
          manual_stopped_at timestamptz,
          completed_at timestamptz,
          error_message text,
          triggered_by uuid REFERENCES users(id) ON DELETE SET NULL,
          triggered_tenant_id uuid REFERENCES tenants(id) ON DELETE SET NULL,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

        CREATE INDEX IF NOT EXISTS idx_collection_runs_keyword_stage_status
          ON collection_runs(keyword_master_id, provider, stage, status);
        CREATE INDEX IF NOT EXISTS idx_collection_runs_resume
          ON collection_runs(next_run_at)
          WHERE status = 'daily_limit_reached';
        CREATE INDEX IF NOT EXISTS idx_collection_runs_triggered_tenant
          ON collection_runs(triggered_tenant_id)
          WHERE triggered_tenant_id IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS uq_collection_runs_active
          ON collection_runs(keyword_master_id, provider, stage)
          WHERE status IN ('not_started','running','daily_limit_reached');
        DROP TRIGGER IF EXISTS set_updated_at ON collection_runs;
        CREATE TRIGGER set_updated_at
          BEFORE UPDATE ON collection_runs
          FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

        ALTER TABLE collection_tasks
          ADD COLUMN IF NOT EXISTS run_id bigint REFERENCES collection_runs(id) ON DELETE SET NULL,
          ADD COLUMN IF NOT EXISTS scheduled_biz_date date,
          ADD COLUMN IF NOT EXISTS batch_no int NOT NULL DEFAULT 1,
          ADD COLUMN IF NOT EXISTS page_size int NOT NULL DEFAULT 10,
          ADD COLUMN IF NOT EXISTS cursor_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

        CREATE INDEX IF NOT EXISTS idx_collection_tasks_run
          ON collection_tasks(run_id);
        CREATE INDEX IF NOT EXISTS idx_collection_tasks_run_status_scheduled
          ON collection_tasks(run_id, status, scheduled_at);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP INDEX IF EXISTS idx_collection_tasks_run_status_scheduled;
        DROP INDEX IF EXISTS idx_collection_tasks_run;

        ALTER TABLE collection_tasks
          DROP COLUMN IF EXISTS cursor_snapshot,
          DROP COLUMN IF EXISTS page_size,
          DROP COLUMN IF EXISTS batch_no,
          DROP COLUMN IF EXISTS scheduled_biz_date,
          DROP COLUMN IF EXISTS run_id;

        DROP TRIGGER IF EXISTS set_updated_at ON collection_runs;
        DROP INDEX IF EXISTS uq_collection_runs_active;
        DROP INDEX IF EXISTS idx_collection_runs_triggered_tenant;
        DROP INDEX IF EXISTS idx_collection_runs_resume;
        DROP INDEX IF EXISTS idx_collection_runs_keyword_stage_status;
        DROP TABLE IF EXISTS collection_runs;
        """
    )
